ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

version = 16

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "Levski"
file = "images/levski.png"
startx = 1577
starty = 690
priority = 2
